/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

package com.alipay.sofa.jraft.entity.codec.v2;

public final class LogOutter {
    private LogOutter() {
    }

    public static void registerAllExtensions(com.github.os72.protobuf351.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.github.os72.protobuf351.ExtensionRegistry registry) {
        registerAllExtensions((com.github.os72.protobuf351.ExtensionRegistryLite) registry);
    }

    public interface PBLogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jraft.PBLogEntry)
                                        com.github.os72.protobuf351.MessageOrBuilder {

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         */
        boolean hasType();

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         */
        com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType();

        /**
         * <code>required int64 term = 2;</code>
         */
        boolean hasTerm();

        /**
         * <code>required int64 term = 2;</code>
         */
        long getTerm();

        /**
         * <code>required int64 index = 3;</code>
         */
        boolean hasIndex();

        /**
         * <code>required int64 index = 3;</code>
         */
        long getIndex();

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        java.util.List<com.github.os72.protobuf351.ByteString> getPeersList();

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        int getPeersCount();

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        com.github.os72.protobuf351.ByteString getPeers(int index);

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        java.util.List<com.github.os72.protobuf351.ByteString> getOldPeersList();

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        int getOldPeersCount();

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        com.github.os72.protobuf351.ByteString getOldPeers(int index);

        /**
         * <code>required bytes data = 6;</code>
         */
        boolean hasData();

        /**
         * <code>required bytes data = 6;</code>
         */
        com.github.os72.protobuf351.ByteString getData();

        /**
         * <code>optional int64 checksum = 7;</code>
         */
        boolean hasChecksum();

        /**
         * <code>optional int64 checksum = 7;</code>
         */
        long getChecksum();

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        java.util.List<com.github.os72.protobuf351.ByteString> getLearnersList();

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        int getLearnersCount();

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        com.github.os72.protobuf351.ByteString getLearners(int index);

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        java.util.List<com.github.os72.protobuf351.ByteString> getOldLearnersList();

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        int getOldLearnersCount();

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        com.github.os72.protobuf351.ByteString getOldLearners(int index);
    }

    /**
     * Protobuf type {@code jraft.PBLogEntry}
     */
    public static final class PBLogEntry extends com.github.os72.protobuf351.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jraft.PBLogEntry)
                                                                                               PBLogEntryOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PBLogEntry.newBuilder() to construct.
        private PBLogEntry(com.github.os72.protobuf351.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PBLogEntry() {
            type_ = 0;
            term_ = 0L;
            index_ = 0L;
            peers_ = java.util.Collections.emptyList();
            oldPeers_ = java.util.Collections.emptyList();
            data_ = com.github.os72.protobuf351.ByteString.EMPTY;
            checksum_ = 0L;
            learners_ = java.util.Collections.emptyList();
            oldLearners_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.github.os72.protobuf351.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private PBLogEntry(com.github.os72.protobuf351.CodedInputStream input,
                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                               throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.github.os72.protobuf351.UnknownFieldSet.Builder unknownFields = com.github.os72.protobuf351.UnknownFieldSet
                .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            com.alipay.sofa.jraft.entity.EnumOutter.EntryType value = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                                .valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = rawValue;
                            }
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            term_ = input.readInt64();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            index_ = input.readInt64();
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                                peers_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            peers_.add(input.readBytes());
                            break;
                        }
                        case 42: {
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                oldPeers_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            oldPeers_.add(input.readBytes());
                            break;
                        }
                        case 50: {
                            bitField0_ |= 0x00000008;
                            data_ = input.readBytes();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000010;
                            checksum_ = input.readInt64();
                            break;
                        }
                        case 66: {
                            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                                learners_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>();
                                mutable_bitField0_ |= 0x00000080;
                            }
                            learners_.add(input.readBytes());
                            break;
                        }
                        case 74: {
                            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                                oldLearners_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>();
                                mutable_bitField0_ |= 0x00000100;
                            }
                            oldLearners_.add(input.readBytes());
                            break;
                        }
                    }
                }
            } catch (com.github.os72.protobuf351.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.github.os72.protobuf351.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    peers_ = java.util.Collections.unmodifiableList(peers_);
                }
                if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    oldPeers_ = java.util.Collections.unmodifiableList(oldPeers_);
                }
                if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                    learners_ = java.util.Collections.unmodifiableList(learners_);
                }
                if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                    oldLearners_ = java.util.Collections.unmodifiableList(oldLearners_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.github.os72.protobuf351.Descriptors.Descriptor getDescriptor() {
            return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
        }

        protected com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.class,
                    com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.Builder.class);
        }

        private int             bitField0_;
        public static final int TYPE_FIELD_NUMBER = 1;
        private int             type_;

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .jraft.EntryType type = 1;</code>
         */
        public com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType() {
            com.alipay.sofa.jraft.entity.EnumOutter.EntryType result = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                .valueOf(type_);
            return result == null ? com.alipay.sofa.jraft.entity.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN : result;
        }

        public static final int TERM_FIELD_NUMBER = 2;
        private long            term_;

        /**
         * <code>required int64 term = 2;</code>
         */
        public boolean hasTerm() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int64 term = 2;</code>
         */
        public long getTerm() {
            return term_;
        }

        public static final int INDEX_FIELD_NUMBER = 3;
        private long            index_;

        /**
         * <code>required int64 index = 3;</code>
         */
        public boolean hasIndex() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required int64 index = 3;</code>
         */
        public long getIndex() {
            return index_;
        }

        public static final int                                        PEERS_FIELD_NUMBER = 4;
        private java.util.List<com.github.os72.protobuf351.ByteString> peers_;

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        public java.util.List<com.github.os72.protobuf351.ByteString> getPeersList() {
            return peers_;
        }

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        public int getPeersCount() {
            return peers_.size();
        }

        /**
         * <code>repeated bytes peers = 4;</code>
         */
        public com.github.os72.protobuf351.ByteString getPeers(int index) {
            return peers_.get(index);
        }

        public static final int                                        OLD_PEERS_FIELD_NUMBER = 5;
        private java.util.List<com.github.os72.protobuf351.ByteString> oldPeers_;

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        public java.util.List<com.github.os72.protobuf351.ByteString> getOldPeersList() {
            return oldPeers_;
        }

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        public int getOldPeersCount() {
            return oldPeers_.size();
        }

        /**
         * <code>repeated bytes old_peers = 5;</code>
         */
        public com.github.os72.protobuf351.ByteString getOldPeers(int index) {
            return oldPeers_.get(index);
        }

        public static final int                        DATA_FIELD_NUMBER = 6;
        private com.github.os72.protobuf351.ByteString data_;

        /**
         * <code>required bytes data = 6;</code>
         */
        public boolean hasData() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required bytes data = 6;</code>
         */
        public com.github.os72.protobuf351.ByteString getData() {
            return data_;
        }

        public static final int CHECKSUM_FIELD_NUMBER = 7;
        private long            checksum_;

        /**
         * <code>optional int64 checksum = 7;</code>
         */
        public boolean hasChecksum() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional int64 checksum = 7;</code>
         */
        public long getChecksum() {
            return checksum_;
        }

        public static final int                                        LEARNERS_FIELD_NUMBER = 8;
        private java.util.List<com.github.os72.protobuf351.ByteString> learners_;

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        public java.util.List<com.github.os72.protobuf351.ByteString> getLearnersList() {
            return learners_;
        }

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        public int getLearnersCount() {
            return learners_.size();
        }

        /**
         * <code>repeated bytes learners = 8;</code>
         */
        public com.github.os72.protobuf351.ByteString getLearners(int index) {
            return learners_.get(index);
        }

        public static final int                                        OLD_LEARNERS_FIELD_NUMBER = 9;
        private java.util.List<com.github.os72.protobuf351.ByteString> oldLearners_;

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        public java.util.List<com.github.os72.protobuf351.ByteString> getOldLearnersList() {
            return oldLearners_;
        }

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        public int getOldLearnersCount() {
            return oldLearners_.size();
        }

        /**
         * <code>repeated bytes old_learners = 9;</code>
         */
        public com.github.os72.protobuf351.ByteString getOldLearners(int index) {
            return oldLearners_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTerm()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasIndex()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasData()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.github.os72.protobuf351.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, term_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, index_);
            }
            for (int i = 0; i < peers_.size(); i++) {
                output.writeBytes(4, peers_.get(i));
            }
            for (int i = 0; i < oldPeers_.size(); i++) {
                output.writeBytes(5, oldPeers_.get(i));
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(6, data_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt64(7, checksum_);
            }
            for (int i = 0; i < learners_.size(); i++) {
                output.writeBytes(8, learners_.get(i));
            }
            for (int i = 0; i < oldLearners_.size(); i++) {
                output.writeBytes(9, oldLearners_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.github.os72.protobuf351.CodedOutputStream.computeEnumSize(1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.github.os72.protobuf351.CodedOutputStream.computeInt64Size(2, term_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.github.os72.protobuf351.CodedOutputStream.computeInt64Size(3, index_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < peers_.size(); i++) {
                    dataSize += com.github.os72.protobuf351.CodedOutputStream.computeBytesSizeNoTag(peers_.get(i));
                }
                size += dataSize;
                size += 1 * getPeersList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < oldPeers_.size(); i++) {
                    dataSize += com.github.os72.protobuf351.CodedOutputStream.computeBytesSizeNoTag(oldPeers_.get(i));
                }
                size += dataSize;
                size += 1 * getOldPeersList().size();
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.github.os72.protobuf351.CodedOutputStream.computeBytesSize(6, data_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.github.os72.protobuf351.CodedOutputStream.computeInt64Size(7, checksum_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < learners_.size(); i++) {
                    dataSize += com.github.os72.protobuf351.CodedOutputStream.computeBytesSizeNoTag(learners_.get(i));
                }
                size += dataSize;
                size += 1 * getLearnersList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < oldLearners_.size(); i++) {
                    dataSize += com.github.os72.protobuf351.CodedOutputStream
                        .computeBytesSizeNoTag(oldLearners_.get(i));
                }
                size += dataSize;
                size += 1 * getOldLearnersList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry)) {
                return super.equals(obj);
            }
            com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry other = (com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) obj;

            boolean result = true;
            result = result && (hasType() == other.hasType());
            if (hasType()) {
                result = result && type_ == other.type_;
            }
            result = result && (hasTerm() == other.hasTerm());
            if (hasTerm()) {
                result = result && (getTerm() == other.getTerm());
            }
            result = result && (hasIndex() == other.hasIndex());
            if (hasIndex()) {
                result = result && (getIndex() == other.getIndex());
            }
            result = result && getPeersList().equals(other.getPeersList());
            result = result && getOldPeersList().equals(other.getOldPeersList());
            result = result && (hasData() == other.hasData());
            if (hasData()) {
                result = result && getData().equals(other.getData());
            }
            result = result && (hasChecksum() == other.hasChecksum());
            if (hasChecksum()) {
                result = result && (getChecksum() == other.getChecksum());
            }
            result = result && getLearnersList().equals(other.getLearnersList());
            result = result && getOldLearnersList().equals(other.getOldLearnersList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasType()) {
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + type_;
            }
            if (hasTerm()) {
                hash = (37 * hash) + TERM_FIELD_NUMBER;
                hash = (53 * hash) + com.github.os72.protobuf351.Internal.hashLong(getTerm());
            }
            if (hasIndex()) {
                hash = (37 * hash) + INDEX_FIELD_NUMBER;
                hash = (53 * hash) + com.github.os72.protobuf351.Internal.hashLong(getIndex());
            }
            if (getPeersCount() > 0) {
                hash = (37 * hash) + PEERS_FIELD_NUMBER;
                hash = (53 * hash) + getPeersList().hashCode();
            }
            if (getOldPeersCount() > 0) {
                hash = (37 * hash) + OLD_PEERS_FIELD_NUMBER;
                hash = (53 * hash) + getOldPeersList().hashCode();
            }
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            if (hasChecksum()) {
                hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
                hash = (53 * hash) + com.github.os72.protobuf351.Internal.hashLong(getChecksum());
            }
            if (getLearnersCount() > 0) {
                hash = (37 * hash) + LEARNERS_FIELD_NUMBER;
                hash = (53 * hash) + getLearnersList().hashCode();
            }
            if (getOldLearnersCount() > 0) {
                hash = (37 * hash) + OLD_LEARNERS_FIELD_NUMBER;
                hash = (53 * hash) + getOldLearnersList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.nio.ByteBuffer data)
                                                                                                                    throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.nio.ByteBuffer data,
                                                                                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.github.os72.protobuf351.ByteString data)
                                                                                                                                       throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.github.os72.protobuf351.ByteString data,
                                                                                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(byte[] data)
                                                                                                       throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(byte[] data,
                                                                                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws com.github.os72.protobuf351.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.io.InputStream input)
                                                                                                                     throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(java.io.InputStream input,
                                                                                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseDelimitedFrom(java.io.InputStream input)
                                                                                                                              throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseDelimitedFrom(java.io.InputStream input,
                                                                                                    com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                        throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.github.os72.protobuf351.CodedInputStream input)
                                                                                                                                              throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parseFrom(com.github.os72.protobuf351.CodedInputStream input,
                                                                                           com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                               throws java.io.IOException {
            return com.github.os72.protobuf351.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.github.os72.protobuf351.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code jraft.PBLogEntry}
         */
        public static final class Builder extends com.github.os72.protobuf351.GeneratedMessageV3.Builder<Builder>
                                                                                                                 implements
                                                                                                                 // @@protoc_insertion_point(builder_implements:jraft.PBLogEntry)
                                                                                                                 com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntryOrBuilder {
            public static final com.github.os72.protobuf351.Descriptors.Descriptor getDescriptor() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
            }

            protected com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.class,
                        com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.Builder.class);
            }

            // Construct using com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.github.os72.protobuf351.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.github.os72.protobuf351.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                term_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                index_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                peers_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
                oldPeers_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                data_ = com.github.os72.protobuf351.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000020);
                checksum_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000040);
                learners_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000080);
                oldLearners_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000100);
                return this;
            }

            public com.github.os72.protobuf351.Descriptors.Descriptor getDescriptorForType() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.internal_static_jraft_PBLogEntry_descriptor;
            }

            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstanceForType() {
                return com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.getDefaultInstance();
            }

            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry build() {
                com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry buildPartial() {
                com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry result = new com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry(
                    this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.term_ = term_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.index_ = index_;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    peers_ = java.util.Collections.unmodifiableList(peers_);
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.peers_ = peers_;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    oldPeers_ = java.util.Collections.unmodifiableList(oldPeers_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.oldPeers_ = oldPeers_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.data_ = data_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.checksum_ = checksum_;
                if (((bitField0_ & 0x00000080) == 0x00000080)) {
                    learners_ = java.util.Collections.unmodifiableList(learners_);
                    bitField0_ = (bitField0_ & ~0x00000080);
                }
                result.learners_ = learners_;
                if (((bitField0_ & 0x00000100) == 0x00000100)) {
                    oldLearners_ = java.util.Collections.unmodifiableList(oldLearners_);
                    bitField0_ = (bitField0_ & ~0x00000100);
                }
                result.oldLearners_ = oldLearners_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.github.os72.protobuf351.Descriptors.FieldDescriptor field,
                                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.github.os72.protobuf351.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.github.os72.protobuf351.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.github.os72.protobuf351.Descriptors.FieldDescriptor field, int index,
                                            java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.github.os72.protobuf351.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.github.os72.protobuf351.Message other) {
                if (other instanceof com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) {
                    return mergeFrom((com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry other) {
                if (other == com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry.getDefaultInstance())
                    return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasTerm()) {
                    setTerm(other.getTerm());
                }
                if (other.hasIndex()) {
                    setIndex(other.getIndex());
                }
                if (!other.peers_.isEmpty()) {
                    if (peers_.isEmpty()) {
                        peers_ = other.peers_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensurePeersIsMutable();
                        peers_.addAll(other.peers_);
                    }
                    onChanged();
                }
                if (!other.oldPeers_.isEmpty()) {
                    if (oldPeers_.isEmpty()) {
                        oldPeers_ = other.oldPeers_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureOldPeersIsMutable();
                        oldPeers_.addAll(other.oldPeers_);
                    }
                    onChanged();
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (other.hasChecksum()) {
                    setChecksum(other.getChecksum());
                }
                if (!other.learners_.isEmpty()) {
                    if (learners_.isEmpty()) {
                        learners_ = other.learners_;
                        bitField0_ = (bitField0_ & ~0x00000080);
                    } else {
                        ensureLearnersIsMutable();
                        learners_.addAll(other.learners_);
                    }
                    onChanged();
                }
                if (!other.oldLearners_.isEmpty()) {
                    if (oldLearners_.isEmpty()) {
                        oldLearners_ = other.oldLearners_;
                        bitField0_ = (bitField0_ & ~0x00000100);
                    } else {
                        ensureOldLearnersIsMutable();
                        oldLearners_.addAll(other.oldLearners_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {
                    return false;
                }
                if (!hasTerm()) {
                    return false;
                }
                if (!hasIndex()) {
                    return false;
                }
                if (!hasData()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.github.os72.protobuf351.CodedInputStream input,
                                     com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                         throws java.io.IOException {
                com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.github.os72.protobuf351.InvalidProtocolBufferException e) {
                    parsedMessage = (com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry) e
                        .getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int type_ = 0;

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             */
            public com.alipay.sofa.jraft.entity.EnumOutter.EntryType getType() {
                com.alipay.sofa.jraft.entity.EnumOutter.EntryType result = com.alipay.sofa.jraft.entity.EnumOutter.EntryType
                    .valueOf(type_);
                return result == null ? com.alipay.sofa.jraft.entity.EnumOutter.EntryType.ENTRY_TYPE_UNKNOWN : result;
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             */
            public Builder setType(com.alipay.sofa.jraft.entity.EnumOutter.EntryType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .jraft.EntryType type = 1;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            private long term_;

            /**
             * <code>required int64 term = 2;</code>
             */
            public boolean hasTerm() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int64 term = 2;</code>
             */
            public long getTerm() {
                return term_;
            }

            /**
             * <code>required int64 term = 2;</code>
             */
            public Builder setTerm(long value) {
                bitField0_ |= 0x00000002;
                term_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 term = 2;</code>
             */
            public Builder clearTerm() {
                bitField0_ = (bitField0_ & ~0x00000002);
                term_ = 0L;
                onChanged();
                return this;
            }

            private long index_;

            /**
             * <code>required int64 index = 3;</code>
             */
            public boolean hasIndex() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required int64 index = 3;</code>
             */
            public long getIndex() {
                return index_;
            }

            /**
             * <code>required int64 index = 3;</code>
             */
            public Builder setIndex(long value) {
                bitField0_ |= 0x00000004;
                index_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 index = 3;</code>
             */
            public Builder clearIndex() {
                bitField0_ = (bitField0_ & ~0x00000004);
                index_ = 0L;
                onChanged();
                return this;
            }

            private java.util.List<com.github.os72.protobuf351.ByteString> peers_ = java.util.Collections.emptyList();

            private void ensurePeersIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    peers_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>(peers_);
                    bitField0_ |= 0x00000008;
                }
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public java.util.List<com.github.os72.protobuf351.ByteString> getPeersList() {
                return java.util.Collections.unmodifiableList(peers_);
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public int getPeersCount() {
                return peers_.size();
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public com.github.os72.protobuf351.ByteString getPeers(int index) {
                return peers_.get(index);
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public Builder setPeers(int index, com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeersIsMutable();
                peers_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public Builder addPeers(com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeersIsMutable();
                peers_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public Builder addAllPeers(java.lang.Iterable<? extends com.github.os72.protobuf351.ByteString> values) {
                ensurePeersIsMutable();
                com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(values, peers_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes peers = 4;</code>
             */
            public Builder clearPeers() {
                peers_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            private java.util.List<com.github.os72.protobuf351.ByteString> oldPeers_ = java.util.Collections
                                                                                         .emptyList();

            private void ensureOldPeersIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    oldPeers_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>(oldPeers_);
                    bitField0_ |= 0x00000010;
                }
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public java.util.List<com.github.os72.protobuf351.ByteString> getOldPeersList() {
                return java.util.Collections.unmodifiableList(oldPeers_);
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public int getOldPeersCount() {
                return oldPeers_.size();
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public com.github.os72.protobuf351.ByteString getOldPeers(int index) {
                return oldPeers_.get(index);
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public Builder setOldPeers(int index, com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldPeersIsMutable();
                oldPeers_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public Builder addOldPeers(com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldPeersIsMutable();
                oldPeers_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public Builder addAllOldPeers(java.lang.Iterable<? extends com.github.os72.protobuf351.ByteString> values) {
                ensureOldPeersIsMutable();
                com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(values, oldPeers_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_peers = 5;</code>
             */
            public Builder clearOldPeers() {
                oldPeers_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            private com.github.os72.protobuf351.ByteString data_ = com.github.os72.protobuf351.ByteString.EMPTY;

            /**
             * <code>required bytes data = 6;</code>
             */
            public boolean hasData() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>required bytes data = 6;</code>
             */
            public com.github.os72.protobuf351.ByteString getData() {
                return data_;
            }

            /**
             * <code>required bytes data = 6;</code>
             */
            public Builder setData(com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes data = 6;</code>
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000020);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private long checksum_;

            /**
             * <code>optional int64 checksum = 7;</code>
             */
            public boolean hasChecksum() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             */
            public long getChecksum() {
                return checksum_;
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             */
            public Builder setChecksum(long value) {
                bitField0_ |= 0x00000040;
                checksum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 checksum = 7;</code>
             */
            public Builder clearChecksum() {
                bitField0_ = (bitField0_ & ~0x00000040);
                checksum_ = 0L;
                onChanged();
                return this;
            }

            private java.util.List<com.github.os72.protobuf351.ByteString> learners_ = java.util.Collections
                                                                                         .emptyList();

            private void ensureLearnersIsMutable() {
                if (!((bitField0_ & 0x00000080) == 0x00000080)) {
                    learners_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>(learners_);
                    bitField0_ |= 0x00000080;
                }
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public java.util.List<com.github.os72.protobuf351.ByteString> getLearnersList() {
                return java.util.Collections.unmodifiableList(learners_);
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public int getLearnersCount() {
                return learners_.size();
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public com.github.os72.protobuf351.ByteString getLearners(int index) {
                return learners_.get(index);
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public Builder setLearners(int index, com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLearnersIsMutable();
                learners_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public Builder addLearners(com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLearnersIsMutable();
                learners_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public Builder addAllLearners(java.lang.Iterable<? extends com.github.os72.protobuf351.ByteString> values) {
                ensureLearnersIsMutable();
                com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(values, learners_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes learners = 8;</code>
             */
            public Builder clearLearners() {
                learners_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000080);
                onChanged();
                return this;
            }

            private java.util.List<com.github.os72.protobuf351.ByteString> oldLearners_ = java.util.Collections
                                                                                            .emptyList();

            private void ensureOldLearnersIsMutable() {
                if (!((bitField0_ & 0x00000100) == 0x00000100)) {
                    oldLearners_ = new java.util.ArrayList<com.github.os72.protobuf351.ByteString>(oldLearners_);
                    bitField0_ |= 0x00000100;
                }
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public java.util.List<com.github.os72.protobuf351.ByteString> getOldLearnersList() {
                return java.util.Collections.unmodifiableList(oldLearners_);
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public int getOldLearnersCount() {
                return oldLearners_.size();
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public com.github.os72.protobuf351.ByteString getOldLearners(int index) {
                return oldLearners_.get(index);
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public Builder setOldLearners(int index, com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldLearnersIsMutable();
                oldLearners_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public Builder addOldLearners(com.github.os72.protobuf351.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureOldLearnersIsMutable();
                oldLearners_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public Builder addAllOldLearners(java.lang.Iterable<? extends com.github.os72.protobuf351.ByteString> values) {
                ensureOldLearnersIsMutable();
                com.github.os72.protobuf351.AbstractMessageLite.Builder.addAll(values, oldLearners_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes old_learners = 9;</code>
             */
            public Builder clearOldLearners() {
                oldLearners_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000100);
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.github.os72.protobuf351.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.github.os72.protobuf351.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:jraft.PBLogEntry)
        }

        // @@protoc_insertion_point(class_scope:jraft.PBLogEntry)
        private static final com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry();
        }

        public static com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.github.os72.protobuf351.Parser<PBLogEntry> PARSER = new com.github.os72.protobuf351.AbstractParser<PBLogEntry>() {
                                                                                      public PBLogEntry parsePartialFrom(com.github.os72.protobuf351.CodedInputStream input,
                                                                                                                         com.github.os72.protobuf351.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                             throws com.github.os72.protobuf351.InvalidProtocolBufferException {
                                                                                          return new PBLogEntry(input,
                                                                                              extensionRegistry);
                                                                                      }
                                                                                  };

        public static com.github.os72.protobuf351.Parser<PBLogEntry> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.os72.protobuf351.Parser<PBLogEntry> getParserForType() {
            return PARSER;
        }

        public com.alipay.sofa.jraft.entity.codec.v2.LogOutter.PBLogEntry getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.github.os72.protobuf351.Descriptors.Descriptor                internal_static_jraft_PBLogEntry_descriptor;
    private static final com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable internal_static_jraft_PBLogEntry_fieldAccessorTable;

    public static com.github.os72.protobuf351.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.github.os72.protobuf351.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\tlog.proto\022\005jraft\032\nenum.proto\"\263\001\n\nPBLog"
                                              + "Entry\022\036\n\004type\030\001 \002(\0162\020.jraft.EntryType\022\014\n"
                                              + "\004term\030\002 \002(\003\022\r\n\005index\030\003 \002(\003\022\r\n\005peers\030\004 \003("
                                              + "\014\022\021\n\told_peers\030\005 \003(\014\022\014\n\004data\030\006 \002(\014\022\020\n\010ch"
                                              + "ecksum\030\007 \001(\003\022\020\n\010learners\030\010 \003(\014\022\024\n\014old_le"
                                              + "arners\030\t \003(\014B2\n%com.alipay.sofa.jraft.en"
                                              + "tity.codec.v2B\tLogOutter" };
        com.github.os72.protobuf351.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.github.os72.protobuf351.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.github.os72.protobuf351.ExtensionRegistry assignDescriptors(com.github.os72.protobuf351.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.github.os72.protobuf351.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.github.os72.protobuf351.Descriptors.FileDescriptor[] { com.alipay.sofa.jraft.entity.EnumOutter
                .getDescriptor(), }, assigner);
        internal_static_jraft_PBLogEntry_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_jraft_PBLogEntry_fieldAccessorTable = new com.github.os72.protobuf351.GeneratedMessageV3.FieldAccessorTable(
            internal_static_jraft_PBLogEntry_descriptor, new java.lang.String[] { "Type", "Term", "Index", "Peers",
            "OldPeers", "Data", "Checksum", "Learners", "OldLearners", });
        com.alipay.sofa.jraft.entity.EnumOutter.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
