##RheaKVStoreOptions
---
clusterName: rhea_benchmark

placementDriverOptions:
  fake: true
  hashRoute: true

storeEngineOptions:
  storageType: Memory
  rocksDBOptions:
    fastSnapshot: true
    dbPath: rhea_benchmark_db
  raftDataPath: rhea_benchmark_raft_data
  raftRpcCoreThreads: 128
  serverAddress:
    ip: 127.0.0.1
    port: 6082
  commonNodeOptions:
    raftOptions:
      readOnlyOptions: ReadOnlyLeaseBased
  regionEngineOptionsList:
    - { regionId: 1, metricsReportPeriod: 30, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 2, metricsReportPeriod: 30, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 3, metricsReportPeriod: 30, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }

onlyLeaderRead: true

failoverRetries: 0
futureTimeoutMillis: 2000
useParallelKVExecutor: false

