##RheaKVStoreOptions
---
clusterName: rhea_benchmark

placementDriverOptions:
  fake: true
  hashRoute: true
  regionRouteTableOptionsList:
    - { regionId:  1,                      }



onlyLeaderRead: true

rpcOptions:
  callbackExecutorCorePoolSize: 0
  callbackExecutorMaximumPoolSize: 0
  rpcTimeoutMillis: 5000

failoverRetries: 1 
futureTimeoutMillis: 5000
useParallelKVExecutor: false

