/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage */

#ifndef _Included_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
#define _Included_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_DEFAULT_FIRST_LOG_INDEX
#define com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_DEFAULT_FIRST_LOG_INDEX 1LL
/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_open
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1open
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_append
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1append
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_get
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1get
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_empty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1empty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_truncate_prefix
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1truncate_1prefix
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_truncate_suffix
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1truncate_1suffix
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage
 * Method:    pmem_log_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_alipay_sofa_jraft_storage_impl_PMemVectorLogStorage_pmem_1log_1clear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
